### ISSUE TITLE
Add scalaJS cross-build example

### ISSUE THREAD

**Issue by boosh** [playframework/play-scala-isolated-slick-example#20]
It'd be awesome if this repo was forked with an example of how to [cross-build](http://www.scala-js.org/doc/project/cross-build.html) ScalaJS with Play configured as per this repo...

**Comment by wsargent** [comment]
@boosh Scala-JS isn't a part of Play, and the projects will typically demo only one thing at a time.  You can see there are multiple examples of Play being used with ScalaJS through Github, so I would use one of those or create your own project.
