### ISSUE TITLE
Can this be used with play-slick?

### ISSUE THREAD

**Issue by mrwillis** [playframework/play-scala-isolated-slick-example#61]
Hi,

I know this example is an isolated example, but are there any examples of using the codegen with play-slick? Can I simply mix in the Table trait generated by slick-codegen into my DAO/Service classes?

Thanks

**Comment by marcospereira** [comment]
Hi @mrwillis,

We don't have an complete example of using play-slick with slick-codegen, but they should work fine together. I'm closing this since it would be better to further discuss it at our forums: https://discuss.playframework.com.
